In [41]:
import numpy as np
import math
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


How many negative numbers are there?

How many positive numbers are there?

How many even positive numbers are there?

If you were to add 3 to each data point, how many positive numbers would there be?

If you squared each number, what would the new mean and standard deviation be?

A common statistical operation on a dataset is centering. This means to adjust the data such that the center of the data is at 0. This is done by subtracting the mean from each data point. Center the data set.

Calculate the z-score for each data point. Recall that the z-score is given by:

In [30]:
#How many negative numbers are there?
len(a[a < 0])

(a>0).sum()

5

In [35]:
# How many positive numbers are there?
print("count of positive numbers:",  (a > 0).sum())

count of positive numbers: 5


In [32]:
# How many even positive numbers are there?

print("count of even positive numbers:", ((a > 0) & (a % 2 == 0)).sum())

count of even positive numbers: 3


In [37]:
# If you were to add 3 to each data point, how many positive numbers would there be?
((a+3) >0).sum()

10

In [46]:
# If you squared each number, what would the new mean and standard deviation be?
mean = (a**2).mean()
(a**2).std()

144.0243035046516

In [47]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [51]:
# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
a = np.array(a)
sum_of_a = a.sum()
sum_of_a

55

In [52]:
## Setup 4
d = [[90, 30, 45, 0, 120, 180], [45, -90, -30, 270, 90, 0], [60, 45, -45, 90, -45, 180]]

d = np.array(d)

In [53]:

# Exercise 1 - Find the sine of all the numbers in d

np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [54]:
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [55]:
# Exercise 6 - Return an array of only the unique numbers in d.

np.unique(d)


array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [56]:
# Exercise 10 - Reshape d into an array of 9 x 2
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])